# 예외 처리

## 1. try, except

형태

```python
try:
    실행할 코드
except [발생 오류[as 오류 메시지 변수]]:
    예외가 발생했을 때 처리하는 코드
```

> [ ] 안의 내용의 사용 여부는 선택이다.(필수가 아님)



- **try, except만 쓰는 방법**

  오류 종류에 상관없이 오류가 발생하면 except 블록을 수행한다.

```python
try:
    ...
except:
    ...
```

> 모든 오류를 잡아냄



-  **발생 오류만 포함한 except문**

  이 경우는 오류가 발생했을 때 except문에 미리 정해 놓은 오류 이름과 일치할 때만 except 블록을 수행한다는 뜻이다.

```python
try:
    ...
except 발생 오류:
    ...
```

> 발생 오류 종류는 정해져 있다.
>
> `except ZeroDivisionError:`  숫자를 0으로 나눠서 에러가 발생했을 때 실행됨
>
> `except IndexError:` 범위를 벗어난 인덱스에 접근하여 에러가 발생했을 때 실행됨



- **발생 오류와 오류 메시지 변수까지 포함한 except문**

  이 경우는 두 번째 경우에서 오류 메시지의 내용까지 알고 싶을 때 사용하는 방법이다.

```python
e = input("division by zero")

try:
    ...
except ZeroDivisionError as e:
    print(e)
```

> 변수에 미리 오류 메시지를 담아놓아야 한다.



## Exception

파이썬 내장 예외처리 클래스 Exception를 상속받아서 예외처리 하는 방법

주로 if문에서 else로 예외상황을 몰아넣었을 때 사용

```
class 예외처리이름(Exception):
	pass
raise 예외처리이름("출력할 구문")
```



```python
score_list = [(i+10) for i in range(90)] + [-1]

grade_list = [0, 0, 0]
for score in score_list:
    if score >=90 and score <100:
        grade_list[0] = grade_list[0] + 1
    elif score >=80 and score <90:
        grade_list[1] = grade_list[1] + 1
    elif score >=0 and score <80:
        grade_list[2] = grade_list[2] + 1
    else:
        class ScoreError(Exception):
            pass
        raise ScoreError("INVALID SCORE")

print(grade_list)
```

```
출력:
raceback (most recent call last):
  File "d:\Project\tmp\.venv\1.py", line 14, in <module>
    raise ScoreError("INVALID SCORE")
__main__.ScoreError: INVALID SCORE
```

