# 예외 처리

## 1. try, except

형태

```python
try:
    실행할 코드
except [발생 오류[as 오류 메시지 변수]]:
    예외가 발생했을 때 처리하는 코드
```

> [ ] 안의 내용의 사용 여부는 선택이다.(필수가 아님)



- **try, except만 쓰는 방법**

  오류 종류에 상관없이 오류가 발생하면 except 블록을 수행한다.

```python
try:
    ...
except:
    ...
```

> 모든 오류를 잡아냄



-  **발생 오류만 포함한 except문**

  이 경우는 오류가 발생했을 때 except문에 미리 정해 놓은 오류 이름과 일치할 때만 except 블록을 수행한다는 뜻이다.

```python
try:
    ...
except 발생 오류:
    ...
```

> 발생 오류 종류는 정해져 있다.
>
> `except ZeroDivisionError:`  숫자를 0으로 나눠서 에러가 발생했을 때 실행됨
>
> `except IndexError:` 범위를 벗어난 인덱스에 접근하여 에러가 발생했을 때 실행됨



- **발생 오류와 오류 메시지 변수까지 포함한 except문**

  이 경우는 두 번째 경우에서 오류 메시지의 내용까지 알고 싶을 때 사용하는 방법이다.

```python
e = input("division by zero")

try:
    ...
except ZeroDivisionError as e:
    print(e)
```

> 변수에 미리 오류 메시지를 담아놓아야 한다.